[Data Whisperer]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Data Analysis Platform"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.61.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pandasai[light]>=2.0.24",
    "plotly>=6.0.0",
    "pyyaml>=6.0.2",
    "streamlit>=1.42.0",
    "xlrd>=2.0.1",
]
